services:
  - type: web
    name: django-blogsite
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn blogsite.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: blogsite.settings
